(autoload 'ido "ido" "Ido mode." t)
(autoload 'magit "magit" "Emacs interface for git." t)
(autoload 'yasnippet "yasnippet" "Snippet expansion." t)
(autoload 'expand-region "expand-region" "Region expansion." t)
(autoload 'paredit "paredit" "Keep paran editing sane." t)
(autoload 'powerline "powerline" "Better mode line." t)
(autoload 'php-mode "php-mode" "Major mode for editing php code." t)
(autoload 'web-mode "web-mode" "Major mode for editing html." t)
(autoload 'clojure-mode "clojure-mode" "Major mode for editing clojure code." t)
