(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)
(if (string= system-type "darwin")
    (setq explicit-shell-file-name "/bin/zsh"))
(setq shell-file-name "zsh")
(setq explicit-bash.exe-args '("--login"))
(setenv "SHELL" shell-file-name)
