#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d 1 2 3
bspc monitor DP-2 -d 4 5 6
bspc monitor DP-4 -d 7 8 9

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# fix for floating emacs
bspc rule -a Emacs state=tiled

# dracula color theme
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
# bspc config presel_feedback_color "#6272a4"

# catppuccin color theme
bspc config normal_border_color "#cdd6f4"
bspc config active_border_color "#eba0ac"
bspc config focused_border_color "#f38ba8"
bspc config presel_feedback_color "#b4befe"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh

